"""empty message

Revision ID: 5bce57126e56
Revises: 8e3a53f9f5e5
Create Date: 2022-05-28 15:08:17.233191

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5bce57126e56'
down_revision = '8e3a53f9f5e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('check_progress', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'check_progress', 'users', ['user_id'], ['id'])
    op.drop_column('check_progress', 'treated_records')
    op.drop_column('check_progress', 'total_records')
    op.add_column('users', sa.Column('login', sa.String(length=255), nullable=True))
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('users', 'login')
    op.add_column('check_progress', sa.Column('total_records', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('check_progress', sa.Column('treated_records', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'check_progress', type_='foreignkey')
    op.drop_column('check_progress', 'user_id')
    # ### end Alembic commands ###
